# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteByName.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_DeleteByName(object):
    def setupUi(self, Form_DeleteByName):
        Form_DeleteByName.setObjectName("Form_DeleteByName")
        Form_DeleteByName.resize(788, 443)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_DeleteByName)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Title_Name = QtWidgets.QLabel(Form_DeleteByName)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_Title_Name.setFont(font)
        self.label_Title_Name.setObjectName("label_Title_Name")
        self.verticalLayout.addWidget(self.label_Title_Name)
        self.textEdit = QtWidgets.QTextEdit(Form_DeleteByName)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_DeleteByName = QtWidgets.QPushButton(Form_DeleteByName)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_DeleteByName.setFont(font)
        self.pushButton_DeleteByName.setObjectName("pushButton_DeleteByName")
        self.horizontalLayout.addWidget(self.pushButton_DeleteByName)
        self.pushButton_Exit = QtWidgets.QPushButton(Form_DeleteByName)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.horizontalLayout.addWidget(self.pushButton_Exit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_Title_Selection = QtWidgets.QLabel(Form_DeleteByName)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_Title_Selection.setFont(font)
        self.label_Title_Selection.setObjectName("label_Title_Selection")
        self.verticalLayout.addWidget(self.label_Title_Selection)
        self.listView = QtWidgets.QListView(Form_DeleteByName)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.listView.setFont(font)
        self.listView.setToolTip("")
        self.listView.setTabKeyNavigation(True)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_DeleteByName)
        self.pushButton_Exit.clicked.connect(Form_DeleteByName.close)
        QtCore.QMetaObject.connectSlotsByName(Form_DeleteByName)

    def retranslateUi(self, Form_DeleteByName):
        _translate = QtCore.QCoreApplication.translate
        Form_DeleteByName.setWindowTitle(_translate("Form_DeleteByName", "根据姓名删除"))
        self.label_Title_Name.setText(_translate("Form_DeleteByName", "输入姓名："))
        self.pushButton_DeleteByName.setText(_translate("Form_DeleteByName", "查找姓名并删除"))
        self.pushButton_Exit.setText(_translate("Form_DeleteByName", "退出"))
        self.pushButton_Exit.setShortcut(_translate("Form_DeleteByName", "Esc"))
        self.label_Title_Selection.setText(_translate("Form_DeleteByName", "选择一条信息以删除："))
