# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_DeleteSelection(object):
    def setupUi(self, Form_DeleteSelection):
        Form_DeleteSelection.setObjectName("Form_DeleteSelection")
        Form_DeleteSelection.resize(568, 191)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_DeleteSelection)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Title = QtWidgets.QLabel(Form_DeleteSelection)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_Title.setFont(font)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout.addWidget(self.label_Title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_DeleteByNumber = QtWidgets.QPushButton(Form_DeleteSelection)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_DeleteByNumber.setFont(font)
        self.pushButton_DeleteByNumber.setObjectName("pushButton_DeleteByNumber")
        self.horizontalLayout.addWidget(self.pushButton_DeleteByNumber)
        self.pushButton_DeleteByName = QtWidgets.QPushButton(Form_DeleteSelection)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_DeleteByName.setFont(font)
        self.pushButton_DeleteByName.setObjectName("pushButton_DeleteByName")
        self.horizontalLayout.addWidget(self.pushButton_DeleteByName)
        self.pushButton_Exit = QtWidgets.QPushButton(Form_DeleteSelection)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.horizontalLayout.addWidget(self.pushButton_Exit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_DeleteSelection)
        self.pushButton_Exit.clicked.connect(Form_DeleteSelection.close)
        QtCore.QMetaObject.connectSlotsByName(Form_DeleteSelection)

    def retranslateUi(self, Form_DeleteSelection):
        _translate = QtCore.QCoreApplication.translate
        Form_DeleteSelection.setWindowTitle(_translate("Form_DeleteSelection", "选择一种方式来删除"))
        self.label_Title.setText(_translate("Form_DeleteSelection", "选择一种删除方式"))
        self.pushButton_DeleteByNumber.setText(_translate("Form_DeleteSelection", "按学号"))
        self.pushButton_DeleteByName.setText(_translate("Form_DeleteSelection", "按名字"))
        self.pushButton_Exit.setText(_translate("Form_DeleteSelection", "取消"))
        self.pushButton_Exit.setShortcut(_translate("Form_DeleteSelection", "Esc"))
