# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteByNumber.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_DeleteByNumber(object):
    def setupUi(self, Form_DeleteByNumber):
        Form_DeleteByNumber.setObjectName("Form_DeleteByNumber")
        Form_DeleteByNumber.resize(548, 187)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_DeleteByNumber)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Title = QtWidgets.QLabel(Form_DeleteByNumber)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.gridLayout.addWidget(self.label_Title, 0, 0, 1, 1)
        self.pushButton_Exit = QtWidgets.QPushButton(Form_DeleteByNumber)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.gridLayout.addWidget(self.pushButton_Exit, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Form_DeleteByNumber)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.pushButton_Delete = QtWidgets.QPushButton(Form_DeleteByNumber)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Delete.setFont(font)
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.gridLayout.addWidget(self.pushButton_Delete, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form_DeleteByNumber)
        self.pushButton_Exit.clicked.connect(Form_DeleteByNumber.close)
        QtCore.QMetaObject.connectSlotsByName(Form_DeleteByNumber)

    def retranslateUi(self, Form_DeleteByNumber):
        _translate = QtCore.QCoreApplication.translate
        Form_DeleteByNumber.setWindowTitle(_translate("Form_DeleteByNumber", "根据学号删除"))
        self.label_Title.setText(_translate("Form_DeleteByNumber", "输入学号："))
        self.pushButton_Exit.setText(_translate("Form_DeleteByNumber", "退出"))
        self.pushButton_Exit.setShortcut(_translate("Form_DeleteByNumber", "Esc"))
        self.pushButton_Delete.setText(_translate("Form_DeleteByNumber", "删除"))
