# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Help(object):
    def setupUi(self, Form_Help):
        Form_Help.setObjectName("Form_Help")
        Form_Help.resize(618, 596)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_Help.sizePolicy().hasHeightForWidth())
        Form_Help.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        Form_Help.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_Help)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Help = QtWidgets.QLabel(Form_Help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Help.sizePolicy().hasHeightForWidth())
        self.label_Help.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_Help.setFont(font)
        self.label_Help.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Help.setObjectName("label_Help")
        self.verticalLayout.addWidget(self.label_Help)

        self.retranslateUi(Form_Help)
        QtCore.QMetaObject.connectSlotsByName(Form_Help)

    def retranslateUi(self, Form_Help):
        _translate = QtCore.QCoreApplication.translate
        Form_Help.setWindowTitle(_translate("Form_Help", "使用说明"))
        self.label_Help.setText(_translate("Form_Help", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ff007f;\">学生管理系统使用说明</span></p><p><span style=\" font-size:11pt; font-weight:600; color:#00aaff;\">基本功能</span></p><p><span style=\" font-size:11pt;\">1. 添加学生信息</span></p><p><span style=\" font-size:11pt;\">点击“添加学生信息”按钮，按照要求输入学号、姓名、年龄、专业、班级等信息即可</span></p><p><span style=\" font-size:11pt;\">注意，学号必须为6位数字；年龄必须在17至25岁之间</span></p><p><span style=\" font-size:11pt; color:#00aa00;\">快捷键：Tab切换文本框、按钮焦点（下同），Alt+A添加一条学生信息，Esc关闭添加页面</span></p><p><span style=\" font-size:11pt;\">2. 删除学生信息</span></p><p><span style=\" font-size:11pt;\">点击“删除学生信息”按钮，选择删除方式，输入相应信息即可确认并删除</span></p><p><span style=\" font-size:11pt;\">注意，如果删除名字重复的同学，需要根据其他信息选择想要删除的学生</span></p><p><span style=\" font-size:11pt;\">3. 修改学生信息</span></p><p><span style=\" font-size:11pt;\">点击“修改学生信息”按钮，可以按照学号或姓名查找并修改</span></p><p><span style=\" font-size:11pt;\">注意，学号不可修改；确认“查找并修改”后，</span><span style=\" font-size:11pt; color:#ff0000;\">当前学生信息将被立即删除</span><span style=\" font-size:11pt;\">，如果希望撤销</span></p><p><span style=\" font-size:11pt;\">此删除，可以在弹出的“修改学生信息”窗口中直接点击“添加”</span></p><p><span style=\" font-size:11pt;\">4. 查询学生信息</span></p><p><span style=\" font-size:11pt;\">点击“查询学生信息”按钮，即可开始查询</span></p><p><span style=\" font-size:11pt; font-weight:600; color:#00aaff;\">其他功能</span></p><p><span style=\" font-size:11pt;\">1. 导出已录入的学生信息至文件</span></p><p><span style=\" font-size:11pt;\">点击菜单栏File-&gt;Save即可保存学生信息，或使用</span><span style=\" font-size:11pt; color:#00aa00;\">快捷键Ctrl+S</span></p><p><span style=\" font-size:11pt;\">2. 从本地文件中读入学生信息</span></p><p><span style=\" font-size:11pt;\">点击菜单栏File-&gt;Open即可读入学生信息，或使用</span><span style=\" font-size:11pt; color:#00aa00;\">快捷键Ctrl+O</span></p></body></html>"))
