# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Modify(object):
    def setupUi(self, Form_Modify):
        Form_Modify.setObjectName("Form_Modify")
        Form_Modify.resize(711, 557)
        self.gridLayout = QtWidgets.QGridLayout(Form_Modify)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Modify_Number = QtWidgets.QLabel(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_Modify_Number.setFont(font)
        self.label_Modify_Number.setObjectName("label_Modify_Number")
        self.gridLayout.addWidget(self.label_Modify_Number, 0, 0, 1, 1)
        self.textEdit_Modify_Number = QtWidgets.QTextEdit(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.textEdit_Modify_Number.setFont(font)
        self.textEdit_Modify_Number.setTabChangesFocus(True)
        self.textEdit_Modify_Number.setObjectName("textEdit_Modify_Number")
        self.gridLayout.addWidget(self.textEdit_Modify_Number, 0, 1, 1, 1)
        self.pushButton_Modify_Number = QtWidgets.QPushButton(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Modify_Number.setFont(font)
        self.pushButton_Modify_Number.setObjectName("pushButton_Modify_Number")
        self.gridLayout.addWidget(self.pushButton_Modify_Number, 0, 2, 1, 1)
        self.label_Modify_Name = QtWidgets.QLabel(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_Modify_Name.setFont(font)
        self.label_Modify_Name.setObjectName("label_Modify_Name")
        self.gridLayout.addWidget(self.label_Modify_Name, 1, 0, 1, 1)
        self.textEdit_Modify_Name = QtWidgets.QTextEdit(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.textEdit_Modify_Name.setFont(font)
        self.textEdit_Modify_Name.setTabChangesFocus(True)
        self.textEdit_Modify_Name.setObjectName("textEdit_Modify_Name")
        self.gridLayout.addWidget(self.textEdit_Modify_Name, 1, 1, 1, 1)
        self.pushButton_Modify_Name = QtWidgets.QPushButton(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Modify_Name.setFont(font)
        self.pushButton_Modify_Name.setObjectName("pushButton_Modify_Name")
        self.gridLayout.addWidget(self.pushButton_Modify_Name, 1, 2, 1, 1)
        self.listView = QtWidgets.QListView(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.listView.setFont(font)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 2, 0, 1, 2)
        self.pushButton_Modify_Exit = QtWidgets.QPushButton(Form_Modify)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Modify_Exit.setFont(font)
        self.pushButton_Modify_Exit.setObjectName("pushButton_Modify_Exit")
        self.gridLayout.addWidget(self.pushButton_Modify_Exit, 2, 2, 1, 1)

        self.retranslateUi(Form_Modify)
        self.pushButton_Modify_Exit.clicked.connect(Form_Modify.close)
        QtCore.QMetaObject.connectSlotsByName(Form_Modify)
        Form_Modify.setTabOrder(self.textEdit_Modify_Number, self.pushButton_Modify_Number)
        Form_Modify.setTabOrder(self.pushButton_Modify_Number, self.textEdit_Modify_Name)
        Form_Modify.setTabOrder(self.textEdit_Modify_Name, self.pushButton_Modify_Name)
        Form_Modify.setTabOrder(self.pushButton_Modify_Name, self.pushButton_Modify_Exit)

    def retranslateUi(self, Form_Modify):
        _translate = QtCore.QCoreApplication.translate
        Form_Modify.setWindowTitle(_translate("Form_Modify", "修改学生信息"))
        self.label_Modify_Number.setText(_translate("Form_Modify", "学号"))
        self.pushButton_Modify_Number.setText(_translate("Form_Modify", "按学号查找并修改"))
        self.pushButton_Modify_Number.setShortcut(_translate("Form_Modify", "Ctrl+S, Ctrl+R"))
        self.label_Modify_Name.setText(_translate("Form_Modify", "姓名"))
        self.pushButton_Modify_Name.setText(_translate("Form_Modify", "按姓名查找并修改"))
        self.pushButton_Modify_Exit.setText(_translate("Form_Modify", "退出"))
        self.pushButton_Modify_Exit.setShortcut(_translate("Form_Modify", "Esc"))
