# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiryShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_QuiryShow(object):
    def setupUi(self, Form_QuiryShow):
        Form_QuiryShow.setObjectName("Form_QuiryShow")
        Form_QuiryShow.resize(682, 401)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_QuiryShow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(Form_QuiryShow)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.listView.setFont(font)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.pushButton_Exit = QtWidgets.QPushButton(Form_QuiryShow)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.verticalLayout.addWidget(self.pushButton_Exit)

        self.retranslateUi(Form_QuiryShow)
        self.pushButton_Exit.clicked.connect(Form_QuiryShow.close)
        QtCore.QMetaObject.connectSlotsByName(Form_QuiryShow)

    def retranslateUi(self, Form_QuiryShow):
        _translate = QtCore.QCoreApplication.translate
        Form_QuiryShow.setWindowTitle(_translate("Form_QuiryShow", "查询结果"))
        self.pushButton_Exit.setText(_translate("Form_QuiryShow", "退出"))
        self.pushButton_Exit.setShortcut(_translate("Form_QuiryShow", "Esc"))
